version: "3"

services: 
  springboot:
    image: springboot
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080" 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
      
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  db-mysql:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root

  loadbalancer:
    container_name: loadbalancer
    image: nginx
    ports:
      - 4000:4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-mysql: