version: "3"

services: 
  springboot:
    image: springboot
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
      
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  db-mysql-dev:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-mysql-dev: