version: "3"

services: 
  springboot-app:
    container_name: spring-app
    image: springbooot-app
    build: .
    ports:
      - 8080:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
      
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  db-mysql:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-mysql: