version: "3"

services: 
  springboot:
    image: springboot
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080" 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    labels:
      com.datadoghq.ad.logs: '[{"source": "java", "service": "springboot", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    depends_on:
      - mysqldb
      
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  db-mysql:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root
    labels:
        com.datadoghq.ad.logs: '[{"source": "mysql", "service": "mysql"}]'

  loadbalancer:
    container_name: loadbalancer
    image: nginx
    ports:
      - 8080:4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "loadbalancer"}]'
    depends_on:
      - springboot

  datadog:
    container_name: datadog
    image: datadog/agent:7
    pid: "host"
    links:
      - springboot
      - mysqldb
      - loadbalancer
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_LOGS_ENABLED=true
    volumes:
      # Note: This configuration is to Linux
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - 8126:8126
#   Enable log collection for the Datadog Agent container
#    labels:
#      com.datadoghq.ad.logs: '[{"source": "agent", "service": "datadog-agent"}]'
    depends_on:
      - springboot
      - mysqldb
      - loadbalancer

volumes:
  db-mysql: