version: "3"

services: 
  springboot:
    image: springboot-dev
    container_name: springboot-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
      
  mysqldb: 
    container_name: mysql-dev
    image: mysql
    volumes:
      -  db-mysql-dev:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: ems
      MYSQL_ROOT_PASSWORD: root

volumes:
  db-mysql-dev: